######################################################################
# Automatically generated by qmake (3.0) ?? ??? 16 17:52:55 2016
######################################################################

TEMPLATE = app
TARGET = mip_lab1
INCLUDEPATH += .

# Input
SOURCES += main.cpp
